### ISSUE TITLE
Relationship Properties

### ISSUE THREAD

**Issue by icaria** [scholrly/neo4django#133]
I understand the intended behaviour is to inherit neo4django.db.models.Relationship in order to add Integer and String properties to Relationships. 

class UserGroupRelationship(Relationship):
    joined = models.DateProperty()

But when I defined a relationship in this way and try to run my tests, I get this error.

Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x101757f50>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 91, in inner_run
    self.validate(display_num_errors=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "path/to/project/models.py", line 14, in <module>
    class UserGroupRelationship(relationships.Relationship):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/neo4django/db/models/relationships.py", line 74, in **new**
    Model = RelationshipModel.new(module, name, modelbases)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/neo4django/db/models/relationships.py", line 121, in new
    '**module**': module,})
TypeError: Error when calling the metaclass bases
    type() argument 2 must be tuple, not list

**Comment by mhluongo** [comment]
Actually, that's the intended _future_ behavior. We don't have relationship models working yet, and it's our longest standing issue (https://github.com/scholrly/neo4django/issues/1). I hope to tackle it next release.

We do have relationship ordering (`preserve_ordering`), which helps in some use cases. For now, you can always add another `NodeModel` in between as a stop-gap and add your properties there, or (if you're interested) hack on RelationshipModels.

**Comment by icaria** [comment]
Thanks for the notice, adding a NodeModel was my initial solution, was just hoping for the more elegant one of Relationship Properties. I'm relatively new to Neo4django so just didn't want to miss anything obvious. I'm glad to know there's plans to implement it. I'll close this.
