### ISSUE TITLE
neo4django.auth.models.User error

### ISSUE THREAD

**Issue by tonjo** [scholrly/neo4django#212]
When sublasssing User from neo4django.auth.models I got this error
launching runserver:

```
myapp.myuser: 'user_ptr' has a relation with model <class 'neo4django.auth.models.User'>, which has either not been installed or is abstract.
```

while myuser is defined as follows:

```
from neo4django.auth.models import User as AuthUser
class myuser( AuthUser):
       pass
```

Has inheritance from neo4django.auth.models been tested by someone?
(in the test suite only the simple authentication is covered)

**Comment by mhluongo** [comment]
This looks familiar- @tonjo is `neo4django.auth` in your `INSTALLED_APPS`?

**Comment by tonjo** [comment]
Yes, it is.
Complete error seen launching `./manage.py runserver` .

```
Unhandled exception in thread started by <bound method Command.inner_run of <django.contrib.staticfiles.management.commands.runserver.Command object at 0x1fb2710>>
Traceback (most recent call last):
  File "/home/tonjo/venv/tuned/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 91, in inner_run
  self.validate(display_num_errors=True)
   File "/home/tonjo/venv/tuned/local/lib/python2.7/site-packages/django/core/management/base.py", line 270, in validate
  raise CommandError("One or more models did not validate:\n%s" % error_text)
django.core.management.base.CommandError: One or more models did not validate:
graph.myuser: 'user_ptr' has a relation with model <class 'neo4django.auth.models.User'>, which has either not been installed or is abstract.
```

**Comment by tonjo** [comment]
With 1.5+ I don't have this issue anymore.
