### ISSUE TITLE
NodeModelManager.exclude not implemented

### ISSUE THREAD

**Issue by tonjo** [scholrly/neo4django#213]
Are there no plans to implement it?
On a NodeQuerySet it is working because it belongs to the "father Django", I suppose.

Sorry if it's not a real issue.

```
>>> User.objects.exclude(username='bill')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 2, in exclude
  File "...[cut].../neo4django/decorators.py", line 54, in not_implemented_dec
  raise NotImplementedError(func.__name__)
NotImplementedError: exclude
```

**Comment by mhluongo** [comment]
Great idea. It should be quick work.

**Comment by tonjo** [comment]
Anyway the quickest way without it is:   

```
 User.objects.all().exclude(username='bill')
```

since objects.all() is a queryset.

**Comment by tonjo** [comment]
Is it difficult to implement? Hints?
