### ISSUE TITLE
neo4django.tests.nodequeryset_tests.test_select_related Regression

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#86]
As reported by http://travis-ci.org/#!/doismellburning/neo4django/jobs/1487451. I can't confirm this on a local machine but I've seen others with the issue- if anyone experiencing it can look into it, that would be great.

**Comment by mhluongo** [comment]
Here's the trace from Travis CI, for the lazy.

# 

## ERROR: neo4django.tests.nodequeryset_tests.test_select_related

Traceback (most recent call last):
  File "/home/vagrant/virtualenv/python2.6/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/builds/doismellburning/neo4django/neo4django/tests/nodequeryset_tests.py", line 511, in test_select_related
    check_dog_hier_from_q(RelatedDog.objects.all().select_related(depth=2))
  File "/home/vagrant/builds/doismellburning/neo4django/neo4django/tests/nodequeryset_tests.py", line 496, in check_dog_hier_from_q
    for d in queryset:
  File "/home/vagrant/virtualenv/python2.6/lib/python2.6/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/home/vagrant/virtualenv/python2.6/lib/python2.6/site-packages/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/home/vagrant/builds/doismellburning/neo4django/neo4django/db/models/query.py", line 634, in iterator
    for model in self.query.execute(using):
  File "/home/vagrant/builds/doismellburning/neo4django/neo4django/db/models/query.py", line 547, in execute
    max_depth=self.max_depth)
  File "/home/vagrant/builds/doismellburning/neo4django/neo4django/db/models/query.py", line 366, in execute_select_related
    new_model = models_so_far[node_id]
KeyError: 262

**Comment by mhluongo** [comment]
@d10genes any chance you can replicate this in your environment? Eg running `nosetests --with-regression neo4django/tests/nodequeryset_tests.py:test_select_related`? I remember we saw this issue on your vm.

**Comment by wcbeard** [comment]
Mine was [similar](https://gist.github.com/2845354), just with a different keyerror.

**Comment by mhluongo** [comment]
Oh, idea! Would it be feasible for you to send me a copy of your vagrant machine? Like the actual vbox, not the config file. Then I'd have a way to replicate and debug this more closely.

**Comment by mhluongo** [comment]
@d10genes would you be interested in playing with this while you still have all the select_related stuff in your head?

**Comment by wcbeard** [comment]
@mhluongo Sure

**Comment by mhluongo** [comment]
That latest still-failing status for 1.7.2 -> http://travis-ci.org/#!/mhluongo/neo4django/jobs/2031734

**Comment by mhluongo** [comment]
@d10genes any progress on this, or do you want me to take it on? If so, do you have any intuitions I should know about before I jump in?

**Comment by mhluongo** [comment]
Looks like this has to do with `get_model()` returning `None` instead of a model class. Looking into how to handle that case.
